name: Node.js + PhantomJS CI / CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
    #- run: export PHANTOMJS_BIN=./phantomjs
    #- run: sudo pkg install phantomjs
    #- run: npm install
    #- run: npm run build --if-present
    #- run: npm test
    #- run: npm run e2e
    - name: Run `npm ci` and `npm run build:ci`
      run: |
        npm ci
        npm run build:ci
